const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
  const page = await browser.newPage({viewport:{width:390,height:844}});
  page.on('dialog', d=>d.accept());const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let stored={title:'東京旅行',destination:'東京',startDate:'2026-10-05',budget:'',transport:'',stay:'',transportCost:'',stayCost:'',days:[{id:'d1',items:[{id:'a',time:'09:00',title:'淺草寺',type:'景點',amount:'',note:''}]}]},revision=1;
  await page.route('**/rest/v1/rpc/*',async route=>{
    if(route.request().url().endsWith('trip_get'))return route.fulfill({json:{trip:stored,revision}});
    stored=route.request().postDataJSON().p_data;revision++;await route.fulfill({json:{status:'updated',revision}});
  });
  await page.route('https://*.wikipedia.org/w/api.php*',async route=>{
    const q=new URL(route.request().url()).searchParams,title=q.get('titles');
    if(title==='連線錯誤')return route.fulfill({status:503,json:{}});
    if(title.startsWith('File:'))return route.fulfill({json:{query:{pages:[{imageinfo:[{descriptionurl:'https://commons.wikimedia.org/wiki/File:Temple.jpg',extmetadata:{Artist:{value:'<a href="https://example.com">Test Photographer</a>'},LicenseShortName:{value:'CC BY-SA 4.0'}}}]}]}}});
    if(title==='淺草寺')return route.fulfill({json:{query:{pages:[{title:'淺草寺',pageprops:{wikibase_item:'Q615183'},thumbnail:{source:'https://thumb.wikimedia.org/test/temple.jpg'},pageimage:'Temple.jpg'}]}}});
    if(title==='同名地點')return route.fulfill({json:{query:{pages:[{title,coordinates:[{}],pageprops:{disambiguation:''},thumbnail:{source:'https://thumb.wikimedia.org/test/temple.jpg'},pageimage:'Temple.jpg'}]}}});
    return route.fulfill({json:{query:{pages:[{title,missing:true}]}}});
  });
  await page.route('https://www.wikidata.org/w/api.php*', route=>route.fulfill({json:{claims:{P625:[{rank:'normal',mainsnak:{datavalue:{value:{latitude:35.71,longitude:139.79}}}}]}}}));
  await page.route('https://thumb.wikimedia.org/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZQAAAABJRU5ErkJggg==','base64')}));
  await page.goto((process.env.TEST_URL||'http://127.0.0.1:8765')+'/?trip=old#key=private-test-key');
  await page.waitForSelector('.photo-credit');
  assert.match(await page.locator('.photo-credit').innerText(),/Test Photographer.*CC BY-SA 4.0/);
  assert.equal(await page.locator('.photo-credit a').count(),0);
  let url=new URL(await page.locator('.map-link').nth(0).getAttribute('href'));
  assert.equal(url.hostname,'www.google.com');assert.equal(url.searchParams.get('query'),'東京 淺草寺');assert.equal(url.hash,'');
  assert.equal(await page.locator('.map-link').nth(0).getAttribute('rel'),'noopener noreferrer');
  await page.locator('[aria-label="編輯 淺草寺"]').click();
  await page.locator('#itemPlaceName').fill('淺草寺');await page.locator('#itemAddress').fill('東京都台東区浅草2丁目3-1');
  await page.locator('#itemForm [type=submit]').click();
  url=new URL(await page.locator('.map-link').nth(0).getAttribute('href'));assert.equal(url.searchParams.get('query'),'東京都台東区浅草2丁目3-1');
  await page.locator('#mapTravelMode').selectOption('walking');
  await page.locator('#addItemBtn').click();await page.locator('#itemTime').fill('11:00');await page.locator('#itemTitle').fill('午餐');await page.locator('#itemPlaceName').fill('同名地點');await page.locator('#itemForm [type=submit]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.place-photo-status')[0]?.textContent.includes('尚無相符'));
  const route=page.getByRole('link',{name:'從上一站出發 ↗'});url=new URL(await route.getAttribute('href'));
  assert.equal(url.searchParams.get('origin'),'東京都台東区浅草2丁目3-1');assert.equal(url.searchParams.get('destination'),'東京 同名地點');assert.equal(url.searchParams.get('travelmode'),'walking');
  assert.equal(await page.locator('.place-photo img').count(),1);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('saveState').textContent==='已儲存');
  assert.equal(stored.mapTravelMode,'walking');assert.equal(stored.days[0].items[0].placeName,'淺草寺');
  await page.reload();await page.waitForSelector('.photo-credit');assert.equal(await page.locator('#mapTravelMode').inputValue(),'walking');
  await page.locator('[aria-label="編輯 淺草寺"]').click();await page.locator('#itemShowPhoto').uncheck();await page.locator('#itemForm [type=submit]').click();assert.equal(await page.locator('.place-photo img').count(),0);
  await page.locator('#addItemBtn').click();await page.locator('#itemTitle').fill('連線錯誤');await page.locator('#itemTime').fill('12:00');await page.locator('#itemForm [type=submit]').click();
  await page.waitForSelector('.photo-retry');assert.match(await page.locator('.photo-retry').innerText(),/重試/);
  assert.equal(await page.locator('.item').last().getByRole('link',{name:'Google 地圖 ↗'}).count(),1);
  assert.deepEqual(errors,[]);
  await browser.close();console.log('Maps/photo checks passed: legacy fallback, addresses, transport/previous stop, attribution, ambiguous/no-match handling, persistence, opt-out, failure fallback and mobile layout.');
})().catch(e=>{console.error(e);process.exit(1);});
