const {test}=require('node:test');
const assert=require('node:assert/strict');
const S=require('../docs/schedule-core.js');
function fixture(){return {items:[{id:'a',title:'A',time:'09:00',durationMinutes:60},{id:'b',title:'B',time:'14:00',durationMinutes:90},{id:'c',title:'C',time:'17:00',durationMinutes:30}],schedule:{enabled:true,startTime:'09:00'}};}
function connect(d,index,m,b=0){const route=S.leg(d,d.items[index],d.items[index+1],'東京','transit');S.putLeg(d,{...route,minutes:m,bufferMinutes:b});}
test('all route and stay durations determine arrivals, including zero and buffer',()=>{const d=fixture();connect(d,0,20,10);connect(d,1,0);const p=S.apply(d,'東京');assert.equal(p.ok,true);assert.deepEqual(d.items.map(x=>x.time),['09:00','10:30','12:00']);assert.equal(p.end,750);assert.equal(p.travelTotal,30);assert.equal(p.stayTotal,180);});
test('missing route leaves all existing times intact',()=>{const d=fixture();connect(d,0,20);const before=structuredClone(d.items);assert.equal(S.apply(d,'東京').missing,1);assert.deepEqual(d.items,before);});
test('location changes and new adjacency require new estimates',()=>{const d=fixture();connect(d,0,20);connect(d,1,10);d.items[1].address='new address';assert.equal(S.apply(d,'東京').missing,2);d.items[1].address='';[d.items[0],d.items[1]]=[d.items[1],d.items[0]];assert.equal(S.apply(d,'東京').missing,2);});
test('explicit route modes persist independently of defaults',()=>{const d=fixture();const saved={...S.leg(d,d.items[0],d.items[1],'東京','walking'),minutes:15};S.putLeg(d,saved);assert.equal(S.leg(d,d.items[0],d.items[1],'東京','driving').mode,'walking');});
test('legacy trips retain original times and default to 60 minute stays',()=>{const d={items:[{id:'b',title:'B',time:'15:00'},{id:'a',title:'A',time:'09:00'}]};const before=structuredClone(d);S.apply(d,'東京');assert.deepEqual(d,before);assert.equal(S.stay(d.items[0]),60);assert.deepEqual(S.ordered(d).map(x=>x.id),['a','b']);});
test('crossing midnight fails atomically; departure at midnight is valid',()=>{const d=fixture();connect(d,0,20);connect(d,1,10);d.schedule.startTime='23:00';const before=structuredClone(d.items);assert.equal(S.apply(d,'東京').ok,false);assert.deepEqual(d.items,before);d.items=d.items.slice(0,1);assert.equal(S.apply(d,'東京').ok,true);assert.equal(S.clock(S.calculate(d,'東京').end),'24:00');});
test('invalid and fractional durations are rejected; midnight is a valid start',()=>{for(const x of ['',null,undefined,-1,1.2,'NaN',1441])assert.throws(()=>S.minutes(x));assert.equal(S.parseTime('00:00'),0);for(const x of ['24:00','12:60','bad'])assert.throws(()=>S.parseTime(x));});
